apiVersion: v1
kind: Pod
metadata:
  name: sleep-20-sec
  #generateName: sleep-20-sec-
  namespace: stress-test
  labels:
    app.kubernetes.io/deploy-on: wec1
spec:
  containers:
  - name: aw-wait-20
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep 20" ]
  restartPolicy: Never
